name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    steps:
    - uses: actions/checkout@v2

    - name: List contents of the project directory
      run: ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: vite-project

    - name: Run Tests
      run: npm run test
      working-directory: vite-project

    - name: Build
      run: npm run build
      working-directory: vite-project
      
    




