name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: website/vite-project/package-lock.json
       

    - name: Install Dependencies
      run: npm ci  
      working-directory: website/vite-project

    - name: Run Tests
      run: npm run test
      working-directory: website/vite-project

    - name: Build
      run: npm run build
      working-directory: website/vite-project
    
    - name: Commit gh-pages
      run: |
        git fetch --all
        git checkout gh-pages
        git config --global user.email "tommytt721@gmail.com"
        git config --global user.name "tommytt-ops"
        git add .
        git commit -m "gh-pages update" || true
        git push origin gh-pages  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



 
