jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'
      working-directory: IoT/website

    - name: Install Dependencies
      run: npm ci
      working-directory: IoT/website

    - name: Run Tests
      run: npm test
      working-directory: IoT/website

    - name: Build
      run: npm run build
      working-directory: IoT/website
