name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: IoT/website  # Updated working directory

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci  # Using npm ci to install dependencies from the lock file

    - name: Run Tests
      run: npm run test

    - name: Build
      run: npm run build  # Assumes you have a build script in your package.json


