name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website # Updated working directory

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: website/package-lock.json
       

    - name: Install Dependencies
      run: npm ci  
      working-directory: vite-project # Updated working directory


    - name: Run Tests
      run: npm run test
      working-directory: vite-project # Updated working directory

    - name: Build
      run: npm run build  # Assumes you have a build script in your package.json
      working-directory: vite-project # Updated working directory
